version: "3.3"

services:

  selenium-hub:
    image: selenium/hub:4.25.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      - SE_OPTS=--log-level FINE
    networks:
      - selenium-grid

  chrome1:
    image: selenium/node-chrome:4.25.0
    container_name: chrome1
    shm_size: 2g
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - selenium-grid

  firefox1:
    image: selenium/node-firefox:4.25.0
    container_name: firefox1
    shm_size: 2g
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - selenium-grid

networks:
  selenium-grid:
    driver: bridge
